/**
 * SPS Cloud Functions - Centralized Error Codes Registry
 * Sprint P1 — Enterprise Production Hardening
 */

const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_FILE: 'INVALID_FILE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  RATE_LIMIT: 'RATE_LIMIT',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  GOOGLE_DRIVE_TIMEOUT: 'GOOGLE_DRIVE_TIMEOUT',
  GOOGLE_DRIVE_UNAVAILABLE: 'GOOGLE_DRIVE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

module.exports = ERROR_CODES;
