/**
 * SPS Cloud Functions - Constants
 */

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  USER: 'USER'
};

const AUDIT_EVENT_TYPES = {
  UPLOAD: "UPLOAD",
  DELETE: "DELETE",
  UPDATE: "UPDATE",
  DOWNLOAD: "DOWNLOAD",
  VIEW: "VIEW",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ROLE_CHANGED: "ROLE_CHANGED",
  USER_DISABLED: "USER_DISABLED",
  USER_ENABLED: "USER_ENABLED",
  RATE_LIMIT: "RATE_LIMIT"
};

const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  PAYLOAD_TOO_LARGE: 413,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500
};

const LOG_CATEGORIES = {
  AUTH: '[AUTH]',
  RBAC: '[RBAC]',
  UPLOAD: '[UPLOAD]',
  DRIVE: '[DRIVE]',
  AUDIT: '[AUDIT]',
  SECURITY: '[SECURITY]',
  FUNCTION: '[FUNCTION]',
  SYSTEM: '[SYSTEM]'
};

const ERROR_CODES = require('./errorCodes');
const { ERROR_CLASSIFICATIONS } = require('./errorClassifications');

module.exports = {
  ROLES,
  AUDIT_EVENT_TYPES,
  HTTP_STATUS,
  LOG_CATEGORIES,
  ERROR_CODES,
  ERROR_CLASSIFICATIONS
};
